steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"]

  # Deploy container image to Cloud Run Jobs
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "jobs"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"
      - "--region"
      - "${_REGION}"
      - "--service-account"
      - "${_SERVICE_ACCOUNT}"
      - "--max-retries"
      - "0"
      - "--memory"
      - "512Mi"
      - "--cpu"
      - "1"
      - "--task-timeout"
      - "540s"

images:
  - "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${_TAG}"

# Substitutions for configurable values
substitutions:
  _SERVICE_NAME: "odoo-bq-sync"
  _REGION: "australia-southeast1"
  _TAG: "latest"
  _SERVICE_ACCOUNT: "odoo-bq-sync@arvautomation.iam.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s
